language: cpp

matrix:
  include:
    - os: linux
      dist: focal
      before-install:
        - sudo apt-get update
        - sudo apt-get -y install ninja-build
        - sudo apt-get -y install "gcc++-10"
      script:
        - "./travis/build-linux.sh"
